import { check, sleep } from 'k6';
import exec from 'k6/execution';
import http from 'k6/http';

const BASE_URL = __ENV.BASE_URL || 'http://127.0.0.1:8080';
const USER_ID =
    __ENV.LOAD_TEST_USER_ID || '00000000-0000-0000-0000-000000000101';
const ASSIGNEE_ID =
    __ENV.LOAD_TEST_ASSIGNEE_ID || '00000000-0000-0000-0000-000000000102';
const PROJECT_ID =
    __ENV.LOAD_TEST_PROJECT_ID || '00000000-0000-0000-0000-000000000301';
const PAGE_SIZE = Number.parseInt(__ENV.LOAD_TEST_PAGE_SIZE || '20', 10);
const VUS = Number.parseInt(__ENV.LOAD_TEST_VUS || '10', 10);
const DURATION = __ENV.LOAD_TEST_DURATION || '30s';

export const options = {
    scenarios: {
        task_workflow: {
            executor: 'constant-vus',
            vus: VUS,
            duration: DURATION,
            gracefulStop: '5s',
        },
    },
    summaryTrendStats: ['avg', 'med', 'p(90)', 'p(95)', 'max'],
    thresholds: {
        http_req_failed: ['rate<0.01'],
        checks: ['rate>0.99'],
        'http_req_duration{endpoint:health}': ['p(95)<100'],
        'http_req_duration{endpoint:ready}': ['p(95)<150'],
        'http_req_duration{endpoint:list_tasks}': ['p(95)<250'],
        'http_req_duration{endpoint:create_task}': ['p(95)<350'],
        'http_req_duration{endpoint:transition_task}': ['p(95)<350'],
        'http_req_duration{endpoint:assign_task}': ['p(95)<350'],
        iteration_duration: ['p(95)<1250'],
    },
};

function request(name, method, path, body, expectedStatus) {
    const params = {
        headers: {
            'Content-Type': 'application/json',
            'X-User-ID': USER_ID,
        },
        tags: { endpoint: name },
    };

    const url = `${BASE_URL}${path}`;
    const response =
        method === 'GET' ? http.get(url, params) : http.post(url, body, params);

    check(response, {
        [`${name} returned ${expectedStatus}`]: (currentResponse) =>
            currentResponse.status === expectedStatus,
    });

    return response;
}

export function setup() {
    const response = http.get(`${BASE_URL}/ready`, { tags: { endpoint: 'ready' } });

    check(response, {
        'setup ready returned 200': (currentResponse) => currentResponse.status === 200,
    });

    if (response.status !== 200) {
        throw new Error(
            `Load test target is not ready: ${response.status} ${response.body}`,
        );
    }
}

export default function () {
    request('health', 'GET', '/health', null, 200);
    request(
        'list_tasks',
        'GET',
        `/v1/tasks?project_id=${PROJECT_ID}&page=1&page_size=${PAGE_SIZE}`,
        null,
        200,
    );

    const suffix = `${exec.vu.idInTest}-${exec.scenario.iterationInTest}-${Date.now()}`;
    const createPayload = JSON.stringify({
        project_id: PROJECT_ID,
        title: `Load test task ${suffix}`,
        description: 'Synthetic workload generated by the k6 scenario.',
        priority: 'medium',
    });

    const createResponse = request(
        'create_task',
        'POST',
        '/v1/tasks',
        createPayload,
        201,
    );

    if (createResponse.status !== 201) {
        sleep(0.2);
        return;
    }

    const taskId = createResponse.json('id');

    request(
        'transition_task',
        'POST',
        `/v1/tasks/${taskId}/transition`,
        JSON.stringify({ status: 'doing' }),
        200,
    );
    request(
        'assign_task',
        'POST',
        `/v1/tasks/${taskId}/assign`,
        JSON.stringify({ user_id: ASSIGNEE_ID }),
        200,
    );
    request('ready', 'GET', '/ready', null, 200);

    sleep(0.2);
}
